### ISSUE TITLE
thread 'main' panicked at 'invalid time',

### ISSUE THREAD

**Issue by azzamsa** [insha/salah#11]
I tried `-6.18233995, 106.84287154` as latitude, longitude. and `2021, 3, 27` as date. and it fails.

However `2021, 2, 27` works.
I tried several date in third months, most of them fails

```rust
use salah::prelude::*;
fn main() {
    let new_york_city = Coordinates::new(-6.18233995, 106.84287154);
    let date = Utc.ymd(2021, 3, 27);
    let params = Configuration::with(Method::NorthAmerica, Madhab::Hanafi);
    let prayers = PrayerSchedule::new()
        .on(date)
        .for_location(new_york_city)
        .with_configuration(params)
        .calculate();

    println!("prayers: {:#?}", prayers);
}
```

```rust
❯ env RUST_BACKTRACE=1 cargo r -- -a
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/bilal -a`
thread 'main' panicked at 'invalid time', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/date.rs:83:42
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::option::expect_failed
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1292:5
   3: core::option::Option<T>::expect
             at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:349:21
   4: chrono::date::Date<Tz>::and_hms
             at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.19/src/date.rs:83:9
   5: salah::astronomy::solar::SolarTime::setting_hour
             at /home/user/.cargo/git/checkouts/salah-7ae9b07792536ea1/d25ffe7/src/astronomy/solar.rs:204:28
   6: salah::astronomy::solar::SolarTime::new
             at /home/user/.cargo/git/checkouts/salah-7ae9b07792536ea1/d25ffe7/src/astronomy/solar.rs:154:21
   7: salah::schedule::PrayerTimes::new
             at /home/user/.cargo/git/checkouts/salah-7ae9b07792536ea1/d25ffe7/src/schedule.rs:44:35
   8: salah::schedule::PrayerSchedule::calculate
             at /home/user/.cargo/git/checkouts/salah-7ae9b07792536ea1/d25ffe7/src/schedule.rs:331:16
   9: bilal::main
             at ./src/main.rs:6:19
  10: core::ops::function::FnOnce::call_once
             at /home/user/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by azzamsa** [comment]
I am very happy that I decided to write my own some days after I stuck with this issue.

https://git.sr.ht/~azzamsa/islam

**Comment by abu-noor** [comment]
It's an overflow with in solar.rs at line: 201. I just added a if statement checking if adjusted_mins is > 59, then subtract 1 from there with a shadow. I'm new to Rust, so there may be a more idiomatic way of checking and adjusting the adjusted. Dunno.
```

  201             let adjusted_mins = (calculated_minutes + calculated_seconds / 60.0).round() as u32;
  202             let mut adjusted_adjusted_mins = 0;
  203             if adjusted_mins > 59 {
  204                 adjusted_adjusted_mins = 1;
  205             }
  206             let adjusted_mins = adjusted_mins - adjusted_adjusted_mins;
```

**Comment by trianglecirclexyz** [comment]
This is still an issue in the latest release, can we reopen? I tried the configuration in the example but with different dates, and a lot of it fails with 'invalid time'  (eg. 9/17/2022).

**Comment by azzamsa** [comment]
I am sorry, I use my own now https://github.com/azzamsa/bilal

**Comment by trianglecirclexyz** [comment]
> I am sorry, I use my own now https://github.com/azzamsa/bilal

Salam, sorry I was referring to the developer of this library to fix it here. Maybe I should make a new issue?

Interesting project btw, will check out.
